version: '3.8'
networks:
  netbasic_net: 
    driver: bridge   
services:
  rottepotatos:
    build: 
      dockerfile: ./src/dockerfile
      context: ./
    ports:
      - "5000:5000"
    networks:
      - netbasic_net        
    restart: always
    environment:
      MONGODB_HOST: mongo
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: exemplo!  
      MONGODB_PORT: 27017
      MONGODB_DB: admin
      MONGODB_URI: "mongodb://root:exemplo!@mongo-test:27017/"

  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:exemplo!@mongo-test:27017/"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo!      
    ports:
      - "27017:27017"
    volumes:
      - /datav:/data/db     
    networks:
      - netbasic_net              
  